Database:
    Host: '127.0.0.1'
    Port: 3306
    User: 'root'
    Password: ''
    DB: 'minecraft'
    Table: 'auth'
SessionEnable: true
SessionExpireTime: 60
LoginTimeout: 60
MessageInterval: 3